klauslaube/apps/media_manager/urls.py
from django.conf.urls import patterns, url

from django.contrib.auth.decorators import login_required

from media_manager.views import MediaAddView, MediaDeleteView, MediaListView

urlpatterns = patterns('',
    url(r'^$', login_required(MediaListView.as_view()), name='media_list'),
    url(r'^add/$', login_required(MediaAddView.as_view()), name='media_add'),
    url(r'^(?P<code>[\w=]+)/delete/$',
        login_required(MediaDeleteView.as_view()), name='media_delete'),
)

klauslaube/apps/portfolio/urls.py
from django.conf.urls import patterns, url
from portfolio.views import JobDetailView, JobListView

urlpatterns = patterns('',
    url(r'^$', JobListView.as_view(), name='job_list'),
    url(r'^(?P<slug>[\w_-]+)/$', JobDetailView.as_view(), name='job_detail'),
)

klauslaube/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.comments.moderation import moderator, AlreadyModerated
from django.db.models import signals

from diario.models import Entry
from diario.sitemaps import DiarioSitemap

from core.feeds import DiarioRssEntriesFeed, DiarioRssEntriesByTagFeed
from core.signals import replace_slideshare_shortcode, EntryModerator
from portfolio.sitemaps import PortfolioSitemap

# Add shortcode to pre_save signal of entry
signals.pre_save.connect(replace_slideshare_shortcode, sender=Entry)
# Let the system send an email when someone comments
try:
    moderator.register(Entry, EntryModerator)
except AlreadyModerated:
    pass

# Autodiscover admin
admin.autodiscover()

# Sitemaps settings
sitemaps = {
    'blog': DiarioSitemap,
    'portfolio': PortfolioSitemap,
}

# URL settings
handler500 = 'views.server_error'

urlpatterns = patterns('',
    # Blog feeds
    url(r'^feed/$', DiarioRssEntriesFeed(), name='diario_feed'),
    url(r'^tag/(?P<tag_name>[^/]+)/feed/$', DiarioRssEntriesByTagFeed(),
        name='diario_tag_feed'),

    # Blog urls
    url(r'', include('diario.urls.entries')),
    url(r'^tag/', include('diario.urls.tagged')),
    url(r'^comentarios/', include('django.contrib.comments.urls')),

    url(r'^portfolio/', include('portfolio.urls', namespace='portfolio')),
    url(r'^contato/', include('simple_contact.urls')),

    # Search urls
    url(r'^busca/', include('haystack.urls')),

    # Sitemap
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {
        'sitemaps': sitemaps
    }, name='sitemap'),

    # Admin urls
    url(r'^admin/media_manager/', include('media_manager.urls',
        namespace='media_manager')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.LOCAL:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

klauslaube/apps/portfolio/models.py
# -*- coding: utf-8 -*-

from datetime import datetime
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from diario.utils import markuping

from portfolio.managers import ActiveManager, JobActiveManager
from portfolio import settings

if settings.HAS_TAG_SUPPORT:
    from tagging.fields import TagField

if settings.HAS_IMAGEKIT_SUPPORT:
    from imagekit.models import ImageSpec
    from imagekit import processors


class Customer(models.Model):
    name = models.CharField(_('Nome'), max_length=100)
    description = models.TextField(_(u'Descrição'), blank=True, null=True)
    website = models.URLField(
        _('Website'),
        verify_exists=False,
        blank=True,
        null=True,
    )
    is_active = models.BooleanField(_('Ativo'), default=True)
    slug = models.SlugField(max_length=100, unique=True)

    objects = models.Manager()
    actives = ActiveManager()

    class Meta:
        verbose_name = _('Cliente')
        verbose_name_plural = _('Clientes')
        ordering = ('name', )

    def __unicode__(self):
        return self.name


class Job(models.Model):
    # Description
    customer = models.ForeignKey(
        Customer,
        verbose_name=_(u'Cliente'),
        blank=True,
        null=True,
    )
    description = models.CharField(_(u'Descrição'), max_length=100)
    details_source = models.TextField(
        _(u'Detalhes'),
        blank=True,
        null=True,
        help_text=_('Escreva utilizando a sintaxe textile'),
    )
    details = models.TextField(_(u'Detalhes em HTML'), blank=True, null=True)
    href = models.URLField(
        _(u'Endereço'),
        verify_exists=False,
        blank=True,
        null=True,
    )
    # Professional description
    my_role = models.CharField(_(u'Meu papel'), max_length=100, blank=True,
        null=True)
    working_regime = models.CharField(
        _(u'Regime de trabalho'),
        max_length=100,
        blank=True,
        null=True,
    )
    i_used_the = models.CharField(
        _(u'O que utilizei'),
        max_length=100,
        blank=True,
        null=True,
    )

    # Image
    sample_image = models.ImageField(
        upload_to='portfolio',
        verbose_name=_(u'Demonstração'),
        blank=True,
        null=True,
    )

    if settings.HAS_IMAGEKIT_SUPPORT:
        thumbnail = ImageSpec(
            [processors.Crop(settings.THUMB_WIDTH, settings.THUMB_HEIGHT, x=0,
                y=0), ],
            format='JPEG',
            image_field='sample_image',
            options={'quality': 90},
        )
        formatted_image = ImageSpec(
            [processors.ResizeToFit(settings.FORMATTED_WIDTH,
                settings.FORMATTED_HEIGHT), ],
            format='JPEG',
            image_field='sample_image',
            options={'quality': 90},
        )

    # Meta
    creation_date = models.DateField(_(u'Data criação'), default=datetime.now)
    is_active = models.BooleanField(_('Ativo'), default=True)
    slug = models.SlugField(max_length=100, unique=True)

    if settings.HAS_TAG_SUPPORT:
        tags = TagField(blank=True)

    objects = models.Manager()
    actives = JobActiveManager()

    class Meta:
        verbose_name = _('Trabalho')
        verbose_name_plural = _('Trabalhos')
        ordering = ('-creation_date', )

    def __unicode__(self):
        return self.description

    def save(self, *args, **kwargs):
        self.details = markuping('textile', self.details_source)
        super(Job, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('portfolio:job_detail', kwargs={
            'slug': self.slug,
        })

klauslaube/apps/seohelper/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _

ROBOT_TAGS = (
    ('index,follow', 'Index, Follow'),
    ('noindex,follow', 'No index, Follow'),
    ('index,nofollow', 'Index, No follow'),
    ('noindex,nofollow', 'No index, No follow'),
)


class Document(models.Model):
    """
    Meta-information for document.
    """
    url = models.CharField(_(u'URL'), max_length=255)
    title = models.CharField(_(u'Título'), max_length=140)
    description = models.TextField(_(u'Descrição'), blank=True, null=True)
    keywords = models.CharField(
        _(u'Palavras-chave'),
        max_length=255,
        blank=True,
        null=True,
    )
    robot_tags = models.CharField(
        _(u'Robots'),
        max_length=20,
        choices=ROBOT_TAGS,
        default=ROBOT_TAGS[0][0],
    )

    class Meta:
        verbose_name = _('Documento')
        verbose_name_plural = _('Documentos')
        ordering = ('url', )

    def __unicode__(self):
        return self.title

klauslaube/apps/media_manager/forms.py
from PIL import Image
import os

from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

PATHS = [('/', 'media'), ]

MANIPULATIONS = (
    ('', _(u'---')),
    ('resize', _(u'Resize')),
)


class ImageUploadForm(forms.Form):
    upload_to = forms.ChoiceField(
        label=_(u'Upload to'),
        choices=PATHS,
        initial=[0][0],
    )
    image = forms.ImageField(label=_(u'Image'))
    manipulation = forms.ChoiceField(
        label=_(u'Image manipulations'),
        choices=MANIPULATIONS,
        required=False,
    )

    width = forms.IntegerField(label=_(u'Width'), required=False)
    height = forms.IntegerField(label=_(u'Height'), required=False)

    def __init__(self, *args, **kwargs):
        tree = None

        # Filled up the upload_to field
        if 'tree' in kwargs:
            tree = kwargs['tree']
            del kwargs['tree']

        super(ImageUploadForm, self).__init__(*args, **kwargs)

        if tree:
            self._fill_upload_to_field(tree)

    def _fill_upload_to_field(self, tree):
        paths = []

        for path in tree:
            path = path.replace(settings.MEDIA_ROOT, '')
            indx = path

            if indx.startswith('/'):
                indx = indx[1:]
            if not indx.endswith('/'):
                indx = '%s/' % indx

            paths.append((indx, indx))

        paths[0] = ('/', 'media/')
        self.fields['upload_to'].choices = paths

    def _save_image(self, image, file_path):
        handler = open(file_path, 'w')
        handler.write(image.read())
        handler.close()

    def _resize_image(self, file_path, width, height):
        image = Image.open(file_path).resize((width, height), Image.ANTIALIAS)
        image.save(file_path)

    def upload(self, *args, **kwargs):
        cdata = self.cleaned_data

        if cdata['upload_to'].startswith('/'):
            cdata['upload_to'] = cdata['upload_to'][1:]

        file_path = os.path.join(settings.MEDIA_ROOT, cdata['upload_to'],
            cdata['image'].name)
        # Save image
        self._save_image(cdata['image'], file_path)

        # Resize image
        if cdata['manipulation'] == 'resize':
            self._resize_image(file_path, cdata['width'],
                cdata['height'])

klauslaube/apps/media_manager/views.py
from base64 import b64decode
import os

from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView
from django.views.generic.edit import DeletionMixin, FormView

from django.contrib import messages

from media_manager.forms import ImageUploadForm
from media_manager.utils import MediaTree


class MediaBaseView(TemplateView):
    def __init__(self, *args, **kwargs):
        super(MediaBaseView, self).__init__(*args, **kwargs)
        self.tree = MediaTree()


class MediaListView(MediaBaseView):
    template_name = 'media_manager/admin/media_list.html'

    def get_context_data(self, **kwargs):
        return {
            'media_list': self.tree.files,
        }


class MediaAddView(FormView):
    form_class = ImageUploadForm
    template_name = 'media_manager/admin/media_add.html'

    def get_form_kwargs(self):
        kwargs = super(MediaAddView, self).get_form_kwargs()
        self.tree = MediaTree()
        kwargs.update({
            'tree': MediaTree().paths,
        })

        return kwargs

    def get_success_url(self):
        return reverse('media_manager:media_list')

    def form_valid(self, form):
        form.upload()
        messages.success(self.request,
            _(u'Image uploaded.'))

        return super(MediaAddView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request,
            _(u'An error occurred while trying to send the form.'))

        return super(MediaAddView, self).form_invalid(form)


class MediaDeleteView(MediaBaseView, DeletionMixin):
    template_name = 'media_manager/admin/media_delete.html'

    def get_context_data(self, **kwargs):
        try:
            kwargs.update({
                'file': self.tree.file_infos(b64decode(kwargs['code'])),
            })
        except:
            raise Http404

        return kwargs

    def delete(self, request, code, *args, **kwargs):
        file_ = self.tree.file_infos(b64decode(code))
        os.remove(file_['path'])
        messages.success(request,
            _('Image removed.'))
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('media_manager:media_list')

klauslaube/apps/portfolio/views.py
from django.views.generic import DetailView, ListView
from portfolio.models import Job
from portfolio import settings


class JobListView(ListView):
    model = Job
    paginated_by = settings.ROWS_PER_PAGE
    queryset = Job.actives.all()


class JobDetailView(DetailView):
    model = Job
    context_object_name = 'job'
    queryset = Job.actives.all()

klauslaube/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext


def server_error(request, template_name='500.html'):
    return render_to_response(template_name,
        context_instance=RequestContext(request))

klauslaube/templates/comments/base.html
{% extends "base.html" %}
{% load i18n %}

{% block meta_robots %}noindex,nofollow{% endblock %}

{% block site_title %}{% trans "Comentários" %}{% endblock %}

{% block content_class %}posts{% endblock %}

klauslaube/templates/comments/form.html
{% load comments i18n %}

<form id="comment-form" action="{% comment_form_target %}" method="post">
    {% csrf_token %}

    <div class="hidden">
        {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}

        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
    </div>

    {% with field=form.name %}
        <p>
            {{ field.label_tag }}

            <input type="text" id="id_name" name="name" maxlength="50"
                {% if field.value %}value="{{ field.value }}"{% endif %}
                placeholder="{% trans "Seu nome ou apelido" %}" required>

            {% if field.help_text %}
                <small class="help-text">{{ field.help_text }}</small>
            {% endif %}

            {{ field.errors }}
        </p>
    {% endwith %}

    {% with field=form.email %}
        <p>
            {{ field.label_tag }}

            <input type="email" id="id_email" name="email"
                {% if field.value %}value="{{ field.value }}"{% endif %}
                placeholder="{% trans "seu-email@provedor.com.br" %}" required>

            {% if field.help_text %}
                <small class="help-text">{{ field.help_text }}</small>
            {% endif %}

            {{ field.errors }}
        </p>
    {% endwith %}

    {% with field=form.url %}
        <p>
            {{ field.label_tag }}

            <input type="url" id="id_url" name="url"
                {% if field.value %}value="{{ field.value }}"{% endif %}
                placeholder="{% trans "http://seu-website.com.br" %}">

            {% if field.help_text %}
                <small class="help-text">{{ field.help_text }}</small>
            {% endif %}

            {{ field.errors }}
        </p>
    {% endwith %}

    {% with field=form.comment %}
        <p>
            {{ field.label_tag }}

            <textarea id="id_comment" name="comment" rows="10" cols="40"
                required placeholder="{% trans "Seu comentário..." %}">{% if field.value %}{{ field.value }}{% endif %}</textarea>

            {% if field.help_text %}
                <small class="help-text">{{ field.help_text }}</small>
            {% endif %}

            {{ field.errors }}
        </p>
    {% endwith %}

    <p>
        <input type="submit" name="submit" value="{% trans "Enviar" %}" class="button">
    </p>
</form>

klauslaube/templates/comments/list.html
{% for comment in comment_list %}
    <article class="comment" id="c{{ comment.id }}" itemprop="comment" itemscope itemtype="http://schema.org/UserComments">
        <header>
            <h4 class="comment-title" itemprop="creator" itemscope itemtype="http://schema.org/Person">
                {% if comment.user_url %}
                    <a href="{{ comment.user_url }}" rel="nofollow" itemprop="name">{{ comment.user_name }}</a>:
                {% else %}
                    <span itemprop="name">{{ comment.user_name }}</span>:
                {% endif %}
            </h4>

            <time datetime="{{ comment.submit_date|date:"Y-m-d\TH:i:s" }}" itemprop="commentTime">
                {{ comment.submit_date|date:"l, d \d\e F \d\e Y. H:i" }}
            </time>
        </header>

        <div itemprop="commentText">{{ comment.comment|linebreaks }}</div>

    </article>
{% endfor %}

klauslaube/templates/comments/preview.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block site_title %}{% trans "Envio de comentários" %}{% endblock %}

{% block content %}
    <h2 class="title">{% trans "Envio de comentários" %}</h2>

    {% if form.errors %}
        <p>{% trans "Por favor, verifique se o formulário abaixo está com os campos obrigatórios preenchidos"  %}.</p>
    {% endif %}

    {% include "comments/form.html" %}
{% endblock %}