klauslaube/apps/media_manager/urls.py
from django.conf.urls import patterns, url

from django.contrib.auth.decorators import login_required

from media_manager.views import MediaAddView, MediaDeleteView, MediaListView

urlpatterns = patterns('',
    url(r'^$', login_required(MediaListView.as_view()), name='media_list'),
    url(r'^add/$', login_required(MediaAddView.as_view()), name='media_add'),
    url(r'^(?P<code>[\w=]+)/delete/$',
        login_required(MediaDeleteView.as_view()), name='media_delete'),
)

klauslaube/apps/portfolio/urls.py
from django.conf.urls import patterns, url
from portfolio.views import JobDetailView, JobListView

urlpatterns = patterns('',
    url(r'^$', JobListView.as_view(), name='job_list'),
    url(r'^(?P<slug>[\w_-]+)/$', JobDetailView.as_view(), name='job_detail'),
)

klauslaube/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.comments.moderation import moderator, AlreadyModerated
from django.db.models import signals

from diario.models import Entry
from diario.sitemaps import DiarioSitemap

from core.feeds import DiarioRssEntriesFeed, DiarioRssEntriesByTagFeed
from core.signals import replace_slideshare_shortcode, EntryModerator
from portfolio.sitemaps import PortfolioSitemap

# Add shortcode to pre_save signal of entry
signals.pre_save.connect(replace_slideshare_shortcode, sender=Entry)
# Let the system send an email when someone comments
try:
    moderator.register(Entry, EntryModerator)
except AlreadyModerated:
    pass

# Autodiscover admin
admin.autodiscover()

# Sitemaps settings
sitemaps = {
    'blog': DiarioSitemap,
    'portfolio': PortfolioSitemap,
}

# URL settings
handler500 = 'views.server_error'

urlpatterns = patterns('',
    # Blog feeds
    url(r'^feed/$', DiarioRssEntriesFeed(), name='diario_feed'),
    url(r'^tag/(?P<tag_name>[^/]+)/feed/$', DiarioRssEntriesByTagFeed(),
        name='diario_tag_feed'),

    # Blog urls
    url(r'', include('diario.urls.entries')),
    url(r'^tag/', include('diario.urls.tagged')),
    url(r'^comentarios/', include('django.contrib.comments.urls')),

    url(r'^portfolio/', include('portfolio.urls', namespace='portfolio')),
    url(r'^contato/', include('simple_contact.urls')),

    # Search urls
    url(r'^busca/', include('haystack.urls')),

    # Sitemap
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {
        'sitemaps': sitemaps
    }, name='sitemap'),

    # Admin urls
    url(r'^admin/media_manager/', include('media_manager.urls',
        namespace='media_manager')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.LOCAL:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

klauslaube/apps/portfolio/models.py
# -*- coding: utf-8 -*-

from datetime import datetime
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from diario.utils import markuping

from portfolio.managers import ActiveManager, JobActiveManager
from portfolio import settings

if settings.HAS_TAG_SUPPORT:
    from tagging.fields import TagField

if settings.HAS_IMAGEKIT_SUPPORT:
    from imagekit.models import ImageSpec
    from imagekit import processors


class Customer(models.Model):
    name = models.CharField(_('Nome'), max_length=100)
    description = models.TextField(_(u'Descrição'), blank=True, null=True)
    website = models.URLField(
        _('Website'),
        verify_exists=False,
        blank=True,
        null=True,
    )
    is_active = models.BooleanField(_('Ativo'), default=True)
    slug = models.SlugField(max_length=100, unique=True)

    objects = models.Manager()
    actives = ActiveManager()

    class Meta:
        verbose_name = _('Cliente')
        verbose_name_plural = _('Clientes')
        ordering = ('name', )

    def __unicode__(self):
        return self.name


class Job(models.Model):
    # Description
    customer = models.ForeignKey(
        Customer,
        verbose_name=_(u'Cliente'),
        blank=True,
        null=True,
    )
    description = models.CharField(_(u'Descrição'), max_length=100)
    details_source = models.TextField(
        _(u'Detalhes'),
        blank=True,
        null=True,
        help_text=_('Escreva utilizando a sintaxe textile'),
    )
    details = models.TextField(_(u'Detalhes em HTML'), blank=True, null=True)
    href = models.URLField(
        _(u'Endereço'),
        verify_exists=False,
        blank=True,
        null=True,
    )
    # Professional description
    my_role = models.CharField(_(u'Meu papel'), max_length=100, blank=True,
        null=True)
    working_regime = models.CharField(
        _(u'Regime de trabalho'),
        max_length=100,
        blank=True,
        null=True,
    )
    i_used_the = models.CharField(
        _(u'O que utilizei'),
        max_length=100,
        blank=True,
        null=True,
    )

    # Image
    sample_image = models.ImageField(
        upload_to='portfolio',
        verbose_name=_(u'Demonstração'),
        blank=True,
        null=True,
    )

    if settings.HAS_IMAGEKIT_SUPPORT:
        thumbnail = ImageSpec(
            [processors.Crop(settings.THUMB_WIDTH, settings.THUMB_HEIGHT, x=0,
                y=0), ],
            format='JPEG',
            image_field='sample_image',
            options={'quality': 90},
        )
        formatted_image = ImageSpec(
            [processors.ResizeToFit(settings.FORMATTED_WIDTH,
                settings.FORMATTED_HEIGHT), ],
            format='JPEG',
            image_field='sample_image',
            options={'quality': 90},
        )

    # Meta
    creation_date = models.DateField(_(u'Data criação'), default=datetime.now)
    is_active = models.BooleanField(_('Ativo'), default=True)
    slug = models.SlugField(max_length=100, unique=True)

    if settings.HAS_TAG_SUPPORT:
        tags = TagField(blank=True)

    objects = models.Manager()
    actives = JobActiveManager()

    class Meta:
        verbose_name = _('Trabalho')
        verbose_name_plural = _('Trabalhos')
        ordering = ('-creation_date', )

    def __unicode__(self):
        return self.description

    def save(self, *args, **kwargs):
        self.details = markuping('textile', self.details_source)
        super(Job, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('portfolio:job_detail', kwargs={
            'slug': self.slug,
        })

klauslaube/apps/seohelper/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _

ROBOT_TAGS = (
    ('index,follow', 'Index, Follow'),
    ('noindex,follow', 'No index, Follow'),
    ('index,nofollow', 'Index, No follow'),
    ('noindex,nofollow', 'No index, No follow'),
)


class Document(models.Model):
    """
    Meta-information for document.
    """
    url = models.CharField(_(u'URL'), max_length=255)
    title = models.CharField(_(u'Título'), max_length=140)
    description = models.TextField(_(u'Descrição'), blank=True, null=True)
    keywords = models.CharField(
        _(u'Palavras-chave'),
        max_length=255,
        blank=True,
        null=True,
    )
    robot_tags = models.CharField(
        _(u'Robots'),
        max_length=20,
        choices=ROBOT_TAGS,
        default=ROBOT_TAGS[0][0],
    )

    class Meta:
        verbose_name = _('Documento')
        verbose_name_plural = _('Documentos')
        ordering = ('url', )

    def __unicode__(self):
        return self.title

klauslaube/apps/media_manager/forms.py
from PIL import Image
import os

from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

PATHS = [('/', 'media'), ]

MANIPULATIONS = (
    ('', _(u'---')),
    ('resize', _(u'Resize')),
)


class ImageUploadForm(forms.Form):
    upload_to = forms.ChoiceField(
        label=_(u'Upload to'),
        choices=PATHS,
        initial=[0][0],
    )
    image = forms.ImageField(label=_(u'Image'))
    manipulation = forms.ChoiceField(
        label=_(u'Image manipulations'),
        choices=MANIPULATIONS,
        required=False,
    )

    width = forms.IntegerField(label=_(u'Width'), required=False)
    height = forms.IntegerField(label=_(u'Height'), required=False)

    def __init__(self, *args, **kwargs):
        tree = None

        # Filled up the upload_to field
        if 'tree' in kwargs:
            tree = kwargs['tree']
            del kwargs['tree']

        super(ImageUploadForm, self).__init__(*args, **kwargs)

        if tree:
            self._fill_upload_to_field(tree)

    def _fill_upload_to_field(self, tree):
        paths = []

        for path in tree:
            path = path.replace(settings.MEDIA_ROOT, '')
            indx = path

            if indx.startswith('/'):
                indx = indx[1:]
            if not indx.endswith('/'):
                indx = '%s/' % indx

            paths.append((indx, indx))

        paths[0] = ('/', 'media/')
        self.fields['upload_to'].choices = paths

    def _save_image(self, image, file_path):
        handler = open(file_path, 'w')
        handler.write(image.read())
        handler.close()

    def _resize_image(self, file_path, width, height):
        image = Image.open(file_path).resize((width, height), Image.ANTIALIAS)
        image.save(file_path)

    def upload(self, *args, **kwargs):
        cdata = self.cleaned_data

        if cdata['upload_to'].startswith('/'):
            cdata['upload_to'] = cdata['upload_to'][1:]

        file_path = os.path.join(settings.MEDIA_ROOT, cdata['upload_to'],
            cdata['image'].name)
        # Save image
        self._save_image(cdata['image'], file_path)

        # Resize image
        if cdata['manipulation'] == 'resize':
            self._resize_image(file_path, cdata['width'],
                cdata['height'])

klauslaube/apps/media_manager/views.py
from base64 import b64decode
import os

from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView
from django.views.generic.edit import DeletionMixin, FormView

from django.contrib import messages

from media_manager.forms import ImageUploadForm
from media_manager.utils import MediaTree


class MediaBaseView(TemplateView):
    def __init__(self, *args, **kwargs):
        super(MediaBaseView, self).__init__(*args, **kwargs)
        self.tree = MediaTree()


class MediaListView(MediaBaseView):
    template_name = 'media_manager/admin/media_list.html'

    def get_context_data(self, **kwargs):
        return {
            'media_list': self.tree.files,
        }


class MediaAddView(FormView):
    form_class = ImageUploadForm
    template_name = 'media_manager/admin/media_add.html'

    def get_form_kwargs(self):
        kwargs = super(MediaAddView, self).get_form_kwargs()
        self.tree = MediaTree()
        kwargs.update({
            'tree': MediaTree().paths,
        })

        return kwargs

    def get_success_url(self):
        return reverse('media_manager:media_list')

    def form_valid(self, form):
        form.upload()
        messages.success(self.request,
            _(u'Image uploaded.'))

        return super(MediaAddView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request,
            _(u'An error occurred while trying to send the form.'))

        return super(MediaAddView, self).form_invalid(form)


class MediaDeleteView(MediaBaseView, DeletionMixin):
    template_name = 'media_manager/admin/media_delete.html'

    def get_context_data(self, **kwargs):
        try:
            kwargs.update({
                'file': self.tree.file_infos(b64decode(kwargs['code'])),
            })
        except:
            raise Http404

        return kwargs

    def delete(self, request, code, *args, **kwargs):
        file_ = self.tree.file_infos(b64decode(code))
        os.remove(file_['path'])
        messages.success(request,
            _('Image removed.'))
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('media_manager:media_list')

klauslaube/apps/portfolio/views.py
from django.views.generic import DetailView, ListView
from portfolio.models import Job
from portfolio import settings


class JobListView(ListView):
    model = Job
    paginated_by = settings.ROWS_PER_PAGE
    queryset = Job.actives.all()


class JobDetailView(DetailView):
    model = Job
    context_object_name = 'job'
    queryset = Job.actives.all()

klauslaube/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext


def server_error(request, template_name='500.html'):
    return render_to_response(template_name,
        context_instance=RequestContext(request))

klauslaube/templates/media_manager/admin/media_add.html
{% extends "admin/base_site.html" %}
{% load i18n adminmedia %}

{% block title %}{% trans "Add image" %}{% endblock %}

{% block extrahead %}{{ block.super }}
{% url 'admin:jsi18n' as jsi18nurl %}
<script type="text/javascript" src="{{ jsi18nurl|default:"../../../jsi18n/" }}"></script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/forms.css" />{% endblock %}

{% block bodyclass %}change-form{% endblock %}

{% block content_title %}<h1>{% trans "Add image" %}</h1>{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="../../">{% trans "Home" %}</a> &rsaquo;
    <a href="../">Media Manager</a> &rsaquo;
    {% trans "Add" %}
</div>
{% endblock %}

{% block content %}<div id="content-main">
    <form action="" method="post" enctype="multipart/form-data" id="media-manager-add-form">
        {% csrf_token %}
        {% if is_popup %}<input type="hidden" name="_popup" value="1" />{% endif %}

        <fieldset class="aligned module wide">
            <div class="form-row upload_to">
                {{ form.upload_to.errors }}
                <div>
                    <label for="id_upload_to" class="required">{% trans "Upload to" %}:</label>
                    {{ form.upload_to }}
                    {{ form.upload_to.help_text }}
                </div>
            </div>

            <div class="form-row image {% if form.image.errors %}errors{% endif %}">
                {{ form.image.errors }}
                <div>
                    <label for="id_image" class="required">{% trans "Image" %}:</label>
                    {{ form.image }}
                    {{ form.image.help_text }}
                </div>
            </div>

            <div class="form-row manipulation {% if form.manipulation.errors %}errors{% endif %}">
                {{ form.manipulation.errors }}
                <div>
                    <label for="id_manipulation" class="required">{% trans "Manipulation" %}:</label>
                    {{ form.manipulation }}
                    {{ form.manipulation.help_text }}
                </div>
            </div>
        </fieldset>

        <fieldset class="aligned module wide">
            <legend>{% trans "Image manipulation" %}</legend>

            <div class="form-row width {% if form.width.errors %}errors{% endif %}">
                {{ form.width.errors }}
                <div>
                    <label for="id_width">{% trans "Width (px)" %}:</label>
                    {{ form.width }}
                    {{ form.width.help_text }}
                </div>
            </div>

            <div class="form-row height {% if form.height.errors %}errors{% endif %}">
                {{ form.height.errors }}
                <div>
                    <label for="id_height">{% trans "Height (px)" %}:</label>
                    {{ form.height }}
                    {{ form.height.help_text }}
                </div>
            </div>
        </fieldset>

        <div class="submit-row">
            <input type="submit" value="Salvar" class="default" name="_save">
        </div>
    </form>
</div>{% endblock %}

klauslaube/templates/media_manager/admin/media_delete.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block title %}{% trans "Are you sure?" %}{{ block.super }}{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="../../../">{% trans "Home" %}</a> &rsaquo;
    <a href="../../">{% trans "Media Manager" %}</a> &rsaquo;
    {% trans "Delete" %}
</div>
{% endblock %}

{% block content_title %}<h1>{% trans "Are you sure?" %}</h1>{% endblock %}

{% block content %}
    <p>{% blocktrans with file.url as url %}Are you sure you want to delete the image
        "{{ url }}" ?{% endblocktrans %}</p>

    <form action="" method="post">
        {% csrf_token %}

        <div>
            <input type="hidden" name="post" value="yes" />
            <input type="submit" value="{% trans "Yes, I'm sure" %}" />
        </div>
    </form>
{% endblock %}

klauslaube/templates/media_manager/admin/media_list.html
{% extends "admin/base_site.html" %}
{% load adminmedia i18n %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/changelists.css" />
    <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/media_list.css" />
{% endblock %}

{% block title %}Media Manager{{ block.super }}{% endblock %}

{% block bodyclass %}change-list{% endblock %}

{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
    <a href="../">{% trans "Home" %}</a> &rsaquo;
    Media Manager
</div>
{% endif %}{% endblock %}

{% block content_title %}<h1>Media Manager</h1>{% endblock %}

{% block content %}
<div id="content-main">
    {% block object-tools %}
        <ul class="object-tools">
            {% block object-tools-items %}
                <li>
                    <a href="add/{% if is_popup %}?_popup=1{% endif %}" class="addlink">
                        {% trans "Add image" %}
                    </a>
                </li>
            {% endblock %}
        </ul>
    {% endblock %}
    <div class="module" id="changelist">
        <form id="changelist-form" action="" method="post">
            {% csrf_token %}

            <table id="result_list">
                <thead>
                    <!--<th class="checkbox-col">#</th>-->
                    <th>{% trans "Preview" %}</th>
                    <th>{% trans "Folder" %}</th>
                    <th>{% trans "File" %}</th>
                    <th>{% trans "Size" %}</th>
                    <th>{% trans "Date" %}</th>
                    <th class="delete-col">{% trans "Delete" %}</th>
                </thead>

                <tbody>
                    {% for file in media_list %}
                        <tr>
                            <!--<td class="checkbox-col"><input type="checkbox" /></td>-->
                            <td class="folder-col">
                                <a href="{{ file.url }}" title="{% trans "Click to view" %}">
                                    <img src="{{ file.url }}" />
                                </a>
                            </td>
                            <td>{{ file.folder }}</td>
                            <td>{{ file.file }}</td>
                            <td>{{ file.size }}</td>
                            <td>{{ file.date }}</td>
                            <td class="delete-col">
                                <a href="{% url media_manager:media_delete code=file.code %}" title="{% trans "Delete image" %}">{% trans "Delete" %}</a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5">{% trans "No media files found" %}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </form>
    </div>
</div>
{% endblock %}